# Generated by Django 6.0.5 on 2026-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('template_key', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=254)),
                ('to', models.JSONField(default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('mode', models.CharField(default='auto', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
