# Generated by Django 5.2.7 on 2026-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='provider',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('brevo', 'Brevo'), ('unknown', 'Unknown')], db_index=True, default='smtp', max_length=30),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='error_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='mode',
            field=models.CharField(choices=[('sync', 'Sync'), ('async', 'Async'), ('auto', 'Auto')], db_index=True, default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='template_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'created_at'], name='email_log_status_7e968e_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['template_key', 'created_at'], name='email_log_templat_eddedd_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['mode', 'status'], name='email_log_mode_eb87b6_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['provider', 'status'], name='email_log_provide_228659_idx'),
        ),
    ]
